spring.application.name=project.2

# ===============================
# CẤU HÌNH KẾT NỐI POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:1602/project2_db
spring.datasource.username=postgres
# Để ẩn mật khẩu trên Git, ta dùng Cú pháp Biến Môi Trường (Environment Variable)
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CẤU HÌNH HIBERNATE / JPA
# ===============================
# Tắt chế độ tự động tạo bảng của Hibernate vì chúng ta dùng file database.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# GẮN FILE DATABASE.SQL ĐỂ CHẠY AUTORUN (Khởi tạo DB)
# ===============================
# Đường dẫn trỏ tới file database.sql ở thư mục ngoài cùng của project
spring.sql.init.mode=always
spring.sql.init.schema-locations=file:database.sql
# Cho phép tiếp tục chạy ứng dụng nếu có một số lỗi (ví dụ bảng đã tồn tại)
spring.sql.init.continue-on-error=true
